services:
  django-application:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/DjangoApp
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_PASS=password
      - DB_USER=user
    depends_on:
      - database

  database:
    image: postgres:14.9-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password